name: Run Aggregator Collect

on:
  schedule:
    # 每天北京时间早上 8:00 和晚上 20:00 自动运行一次 (UTC时间 0:00 和 12:00)
    - cron: '0 0,12 * * *'
  workflow_dispatch: # 允许手动点击按钮触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Collect Script
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        # 请把下面命令中的 "你的GitHub用户名/你的Gist的ID" 替换成你实际的信息
        # Gist ID 获取方式：访问 gist.github.com，新建一个名为 clash.yaml 的空文件并保存，
        # URL 最后的这一串字母数字就是 Gist ID (例如 github.com/用户名/xxxxxxxx)
        run: |
          python subscribe/collect.py -g killermape/88be3385c7b73493a6896f382b4add30 -k ${{ secrets.PUSH_TOKEN }} -t clash v2ray singbox
